//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoSM.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTE
    {
        public string cCodeRest { get; set; }
        public string cNombre { get; set; }
        public string cDireccion { get; set; }
        public string cContacto { get; set; }
        public decimal dLatitud { get; set; }
        public decimal dLongitud { get; set; }
        public string cParking { get; set; }
        public string cInternet { get; set; }
        public string cVisa { get; set; }
        public string cMastercard { get; set; }
        public int eValoracion { get; set; }
        public string cTelefono { get; set; }
        public string cCelular { get; set; }
        public string cHorario { get; set; }
    }
}
